services:
  db:
    image: postgres:15-alpine
    container_name: diplom1c_db
    restart: unless-stopped
    cpus: "1.0"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-Titan}
    mem_limit: 1400m
    mem_reservation: 384m
    memswap_limit: 2g
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      postgres
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c work_mem=8MB
      -c maintenance_work_mem=128MB
      -c max_connections=50

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: diplom1c_server
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-Titan}?schema=public
      PORT: ${PORT:-3001}
      JWT_SECRET: ${JWT_SECRET:-your_super_secret_key_SASHAT}
      BASE_URL: ${BASE_URL:-http://186.246.3.13:3001}
      VK_TOKEN: ${VK_TOKEN:-vk1.a.pqQ5McNGk2eUF4csQJpJq9zlbtl1piRvkaINqtMbygpTxwo_-qCzX3O0JRQhkRYJZawccbBoih93qNSCgiFiHbRbttPmXwqBvogDgNR8wSqYce6XTevxpuAFbPY6Li3gETeMMknMFfvFxLSm_9Uygpa6MV7-dCoMRRjVKJm0Z-baAhACItnxLobAPMdMx74oBxZQubqQ__9qFogx3JUG1Q}
      VK_API_VERSION: ${VK_API_VERSION:-5.131}
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:5173,http://localhost,http://localhost:80,http://186.246.3.13,http://186.246.3.13:80}
    cpus: "0.8"
    mem_limit: 1200m
    mem_reservation: 256m
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server/uploads:/app/uploads

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-/api}
        VITE_BACKEND_URL: ${VITE_BACKEND_URL:-}
        VITE_WS_URL: ${VITE_WS_URL:-}
    container_name: diplom1c_client
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  postgres_data:
    driver: local
