services:
  db:
    image: postgres:15-alpine
    container_name: diplom1c_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Titan
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: diplom1c_server
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/Titan?schema=public
      PORT: 3001
      JWT_SECRET: your_super_secret_key_SASHAT
      BASE_URL: http://186.246.3.13:3001
      VK_TOKEN: vk1.a.pqQ5McNGk2eUF4csQJpJq9zlbtl1piRvkaINqtMbygpTxwo_-qCzX3O0JRQhkRYJZawccbBoih93qNSCgiFiHbRbttPmXwqBvogDgNR8wSqYce6XTevxpuAFbPY6Li3gETeMMknMFfvFxLSm_9Uygpa6MV7-dCoMRRjVKJm0Z-baAhACItnxLobAPMdMx74oBxZQubqQ__9qFogx3JUG1Q
      VK_API_VERSION: 5.131
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server/uploads:/app/uploads

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: diplom1c_client
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  postgres_data:
    driver: local
